version: '3'
services:

  user-management:
    build: ./UserManagement
    container_name: user-management
    ports:
    - 8081:3001

  user-management-ui:
     build: ./user-management-ui
     container_name: user-management-ui
     ports:
       - 8082:3000
     links:
       - user-management











