version: '3'
services:

  user-management:
    build: ./UserManagement
    container_name: user-management
    ports:
    - 3001:3001

  user-management-ui:
     build: ./user-management-ui
     container_name: user-management-ui
     ports:
       - 3000:3000
     links:
       - user-management











